name: shared
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://example.com/shared"
resolution: workspace

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  go_router_modular: ^4.2.0+4
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  talker_flutter: ^4.9.3
  talker_dio_logger: ^4.9.3
  retrofit: ^4.6.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  result_dart: ^2.1.1
  result_command: ^2.1.0
  zod_validation: ^1.0.5
  slang: ^4.8.1
  slang_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
