targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: pt-BR
          input_directory: assets/i18n
          input_file_pattern: .i18n.json
          output_directory: lib/i18n
          output_file_name: translations.g.dart
          generate_enum: false
